### PR TITLE
Update environment variable

### PR DESCRIPTION
**Pull request by chadq**
The previous commit failed as it seems like the environment variable for the s3path wasn't stored between commands.

@kian

### CODE REVIEW

**Comment by chadq** [comment]
@kian something like below may work as well.

```
deployment:
  release:
    branch: master
    owner: makethunder
    commands:
      -> s3path="s3://s3.aws.paperg.com/circleci/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/" \
         aws s3 cp debian-paperg.sh "${s3path}/debian-paperg.sh"
```

**Comment by kian** [comment]
Just use a single command (no s3path variable)

```
- aws s3 cp debian-paperg.sh s3://s3.aws.paperg.com/circleci/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/
```

That should work

**Comment by chadq** [comment]
@kian are we concerned about the line length?

**Comment by kian** [comment]
@chadq nice to keep it < 80 chars, but don't worry about it here

**Pull request closed without merging**
